### PR TITLE
Sign or upload to match comps

### PR DESCRIPTION
**Pull request by jeremiak**
According to the [design comps](https://gsa.invisionapp.com/share/4Z4X4ALYB#/screens/115178939), the user should either sign the manifest or upload a scanned version of the manifest.

This PR makes the views capable of this sort of user flow, though currently there is no validation. That is to say that the user could just as easily not submit a scanned version with this version of the PR.

However, this sets up the UI so that the flow is consistent with the design comps.

### CODE REVIEW

**Comment by pkarman** [comment]
@jeremiak some merge conflicts here. My guess is whitespace in the app.js file. I tried to standardize on 2 space indent in #14 since _most_ of the code was already that way.

**Comment by jeremiak** [comment]
Merge conflicts fixed (was partially whitespace) but tests that came in from `master` aren't passing for some reason now

**Comment by pkarman** [comment]
@jeremiak I will investigate test failures.

**Comment by pkarman** [comment]
tests are all passing for me locally. I can't figure out how to trigger travis rebuild manually, so going to make a trivial change to the branch to trigger.

**Comment by pkarman** [comment]
The problem is that `rspec-mocks 3.4.1` breaks the `receive` behavior of previous versions. Working on fix now.

**Pull request merged**
