### PR TITLE
Add code climate config file

### PR DESCRIPTION
**Pull request by jessieay**

### CODE REVIEW

**Comment by pkarman** [comment]
happy to merge once we figure out the codeclimate failure.

**Comment by jessieay** [comment]
@pkarman just deleted code climate on my side if you want to re-add. I am not sure how to add from the 18F acct (same problem as w C2)

**Comment by pkarman** [comment]
I tried re-adding.

also, want to add to README?

```
[![Code Climate](https://codeclimate.com/github/18F/e-manifest/badges/gpa.svg)](https://codeclimate.com/github/18F/e-manifest)
```

**Comment by pkarman** [comment]
@jessieay is this still relevant now that `Gemfile.lock` is in git?

**Comment by jessieay** [comment]
@pkarman rebased against master and  added badge to README. 

I am unable to add the PR hook because I am not a member of the 18F code climate org.

**Comment by pkarman** [comment]
I have added the hook (I think).

**Pull request merged**
