### PR TITLE
revert manifests.content back to json column type

### PR DESCRIPTION
**Pull request by pkarman**
see discussion on #74

### CODE REVIEW

**Comment by jessieay** [comment]
cool - let's update our travis settings to use 9.3 then, too. (currently uses 9.4)

**Comment by pkarman** [comment]
@jessieay will do, one sec.

**Comment by jessieay** [comment]
for those of us who have already run this migration in its old form, what will be the best way to update? `rake db:migrate` won't be problematic?

**Comment by pkarman** [comment]
@jessieay I don't think it will be. If you have already run it, this will migrate it back. If you haven't run it, it will basically do nothing (just tested that at cloud.gov).

**Pull request merged**
