### PR TITLE
Validate presence of manifest tracking number

### PR DESCRIPTION
**Pull request by jessieay**
- This is the only required field for a manifest

### CODE REVIEW

**Comment by jessieay** [comment]
Im having a hard time figuring out where the CC failure is - help!

screen shot 2016-01-14 at 12 00 17 pm

**Comment by brandocalrissian** [comment]
From sprint planning today: we need the manifest tracking number to be submitted with an image.

**Comment by jessieay** [comment]
ok, this PR now validates presence of manifest tracking # ALWAYS!

**Comment by brandocalrissian** [comment]
Can we document the HTTP 422 validation error response in our swagger docs?

No other comments-- looks good. I merged the latest master to play around with it.

**Pull request merged**
