### PR TITLE
Add helpful error messages for web when invalid manifest

### PR DESCRIPTION
**Pull request by jessieay**
- Formerly, was showing json_schema errors first, which were hard to
  understand

Before:

screen shot 2016-01-26 at 3 00 57 pm

After:

screen shot 2016-01-26 at 3 01 06 pm

### CODE REVIEW

**Comment by pkarman** [comment]
a visual nit: I could not see the error message in the "after" screenshot at first because it is in the blue header banner. Could we stick it in the body, framed in some kind of border/color?

**Comment by jessieay** [comment]
Do you think we would move the location of all flashes? Would be annoying
to move one type and not all.

**Comment by pkarman** [comment]
Yes I would move them all.

**Comment by jessieay** [comment]
@pkarman just realized that this is not the branch with the updated flash styles. Here is a screenshot of a flash from https://github.com/18F/e-manifest/pull/117

screen shot 2016-01-27 at 10 08 43 am

you still think we should move it?

**Comment by pkarman** [comment]
ah that's much better. no need to move it.

**Pull request merged**
