### PR TITLE
Dev setup

### PR DESCRIPTION
**Pull request by pkarman**
Some small changes I observed when bootstrapping for the first time.

### CODE REVIEW

**Comment by brandocalrissian** [comment]
Do you want to add the alternative dotenv configuration to the README so new devs know it's an option without looking through code?

**Comment by pkarman** [comment]
@brandocalrissian happy to do that. Going to also add a test first for dotenv config, so marking this PR as WIP.

**Comment by brandocalrissian** [comment]
@pkarman sounds good!

**Comment by pkarman** [comment]
@brandocalrissian this is ready for your review now.

**Comment by brandocalrissian** [comment]
Thanks!

**Pull request merged**
