### PR TITLE
Add analytics code to app

### PR DESCRIPTION
**Pull request by jessieay**
- In Rails prod env only
- JS copied from https://github.com/18F/e-manifest/blob/57acbd249ebf44b8289d0e116da4fa189bef84f2/_static/_layouts/template/main.html#L24
- https://trello.com/c/2apE6dE7

### CODE REVIEW

**Comment by pkarman** [comment]
lovely.

any idea if we need to also add:

```
    {% if jekyll.environment == "production" %}
    <script src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js" id="_fed_an_ua_tag"></script>
    {% endif %}
```

to the footer? it's in the old `_static/_layouts/template/main.html` footer.

**Comment by jeremiak** [comment]
@pkarman we absolutely do want to add DAP (in addition to the other Google Analytics) onto the site per the [18F analytics standards](https://github.com/18F/analytics-standards#digital-analytics-program-snippet)

**Comment by jessieay** [comment]
good call! added at fbb35ac5589b1acf6d86e13501b3e2519acaafd3

**Comment by pkarman** [comment]
@jessie: According to the DAP page:

> Note: The above _script_ tag is loaded synchronously, so you should put it at the bottom of your 
> HTML. DAP has an outstanding bug affecting asynchronous usage.

**Comment by jeremiak** [comment]
@pkarman am I missing something? It looks like this analytics snippet is at the bottom of the body in the HTML document. The only time it isn't is when the `env` is `test`, in which case the analytics snippet won't be loaded anyway.

**Comment by jessieay** [comment]
Yes, I believe this is at the bottom unless I too am missing something. I inserted it where it was previously (below GA code).

**Comment by pkarman** [comment]
Ah then I am confused. Sorry. In the Sinatra version, the GA code was in the _head_ and the DAP code was in the footer (end of body).

**Comment by jessieay** [comment]
@pkarman moved stuff around 425d7c169775d0dbc4b99dc2b9fa0cb374be1a64

**Comment by jessieay** [comment]
you were right, GA recommends analytics to be before closing head tag: 

> Paste your snippet (unaltered, in its entirety) into every web page you want to track. Paste it immediately before the closing </head> tag

https://support.google.com/analytics/answer/1008080?hl=en

**Comment by pkarman** [comment]
:+1:

**Pull request merged**
