### PR TITLE
Reskins web.html for Victor's styling, part 1

### PR DESCRIPTION
**Pull request by baccigalupi**
@brandocalrissian Not ready for primetime yet. Can you comment/help with next steps?

```
    This commit adds main.css to the web.html stylesheet include.

    I think this is not the best way to do it, but I wasn't able
    to create a web.scss that compiled to web.css. Jekyll is in my
    way! That has meant that I am undoing a lot of the efforts of
    main.css in other parts in order to get this to work.

    Also, I don't know the product flow so matching Victor's mockups
    to pages is not something I can do.

    One last note: the pages around signing don't have a layout and
    I am not sure whether I introduced that or whether it was
    intentional.
```

### CODE REVIEW

**Comment by brandocalrissian** [comment]
I can move the main.scss changes into a web.scss and get it included in the template.

Perhaps it's a good idea to address all of these concerns here instead of splitting them out to Trello.

Here goes...

---

To generate a new css with jekyll's built-in sass toolchain, in this case

1) Create a web.scss file in _static/assets/css
2) Make sure the file starts with two lines of three hyphens (special jekyll indicators from http://jekyllrb.com/docs/assets/)
3) Sass it up!

The generated css will appear in public/assets/css/web.css

I pushed a temporary branch demonstrating this file creation at 18F/e-manifest: https://github.com/18F/e-manifest/commit/c2c38b030bbea663b8c4b8b41dccf9f89b62766f

---

The signing pages don't have a direct layout-- they are conditionally displayed parts of sign.html. sign.html manages the state machine logic for signing a manifest and also references the web.html template.

---

From the Grid view in Invision, the mocks are laid out in order. 
1. Home page
2. Filtered version of home page (i.e. searched for something on the side, filtered the results down)
3. The view you're taken to if you click on one of the results on the home/search page.
4. If you click on "industry" in the menu at any time.
5. If you click on "upload scan"
6. If, in # 4, you had clicked on "Submit via form"
7. If you are submitting via the form, you're taken here and given the option to sign or upload.
8. If you hit "upload" on # 7, you're taken here. 
9. If you hit "sign" on # 7, you're taken here.
10. After you log in on # 9.
11. After you hit "sign." "Home" returns you to #1, "new manifest" to # 4.

Clearly we should rename some files. The html files corresponding to each Invision view are:
1. Home page: search.html
2. Filtered home page: search.html
3. Manifest detail: manifest-detail.html
4. Industry "home": manifest-mainpage.html
5. Upload: bulk-upload.html
6. Manifest entry form: industry.html
7. Sign or upload form: doesn't exist yet
8. Upload: seems like duplicate of 5 (bulk-upload.html)
9. Signing authentication: sign-login.html
10. Signing answer: sign-answer.html
11. Signing confirmation: sign-confirmation.html

**Comment by brandocalrissian** [comment]
I moved the sass changes to a web.scss in https://github.com/18F/e-manifest/commit/f7e89318971eed8b4c1fed32761b37011f19f6c6. I meant to reference this issue but pushed to origin too fast like a rookie.

Do you think this branch now satisfies https://trello.com/c/tAPdOGms (Make main template match v2 comps)? I think it does, but would like your confirmation. The only thing that seems out of place is having the "about" header item try to link to a non-existent route. There are some URL candidates for this link-- I'll ask the product owner.

**Comment by baccigalupi** [comment]
I just rebased off master. If this feels like it fits the layout changes I am good with finishing this story. What is the process for pushing to master or merging this pull request? You do it? I do it?

**Comment by baccigalupi** [comment]
I just sent through a new commit for the home/search restyle. Since these work on top of each other, I can keep sending through commits to get through the rest of the restyle stories, or these can be folded in one at a time.

@brandocalrissian let me know which way you prefer

**Comment by brandocalrissian** [comment]
I'll merge this in soon. Then we can go forward with a branch per story once this is merged.

**Pull request merged**
